const productos = [
  {
    id: "MLA1101874413",
    title: "Cartucho Hp 664  Tricolor Original",
    image: "http://http2.mlstatic.com/D_754420-MLA47385966422_092021-O.jpg",
    price: 10299,
    category: "MLA7415",
    stock: 200,
    sold: 500,
    description:
      "Para impresoras HP modelos: 3635, 4535, 4675 Imprima sus documentos con alta calidad, utilizando los cartuchos diseñados para ofrecer un rendimiento libre de preocupaciones y resultados uniformes en los que puede contar. Los cartuchos originales HP que se adaptan a su forma de vivir, jugar e imprimir Rendimienro de hasta 120 páginas",
    AdminUser: "NULL",
  },
  {
    id: "MLA1101999424",
    title: "Cartucho Hp 667 Tricolor Original",
    image: "http://http2.mlstatic.com/D_940081-MLA47388782152_092021-O.jpg",
    price: 10619,
    category: "MLA7415",
    stock: 1,
    sold: 500,
    description:
      "Cartucho de Tinta para Impresora Compatibilidad de hardware: HP Deskjet Plus Ink Advantage 6000, HP DeskJet Plus Ink Advantage 6400, and HP Deskjet Ink Advantage 1200 series printers and HP Deskjet Ink Advantage 2300, HP Deskjet Ink Advantage 2700, and HP DeskJet Ink Advantage 4100 All-in-One printers",
    AdminUser: "NULL",
  },
  {
    id: "MLA1102136009",
    title: "Botella De Tinta Hp Gt52 - Amarillo",
    image: "http://http2.mlstatic.com/D_946962-MLA47396593375_092021-O.jpg",
    price: 10299,
    category: "MLA3561",
    stock: 1,
    sold: 500,
    description:
      "Imprima miles de páginas a un costo por página extremadamente bajo[1]. Es sencillo con este sistema de tanques de tinta HP de alta capacidad. Imprima todo lo que quiera sin preocuparse por el costo de la tinta utilizando botellas de tinta original HP de alta capacidad[1]. Imprima una y otra vez. Imprima miles de páginas gracias a las botellas de tinta HP original.[2]Trabaje con menos interrupciones: imprima página tras página sin preocuparse por recargar tinta. Cause una buena impresión con la excelente calidad y confiabilidad de impresión de HP. Con las tintas originales HP, imprima documentos nítidos con texto negro nítido.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1102149101",
    title: "Tinta Negra Hp Gt53 Botella Original",
    image: "http://http2.mlstatic.com/D_612747-MLA69360469776_052023-O.jpg",
    price: 10299,
    category: "MLA3561",
    stock: 1,
    sold: 500,
    description:
      "Cartuchos Y Cabezales De Impresión  Rendimiento: 4000  Rendimiento De La Página (Blanco Y Negro): 4.000 páginas  Color(Es) De Consumibles De Impresión: Negro  Tipos De Tinta: Con base de pigmento Dimensiones  Dimensiones Mínimas (Anch. X Prof. X Alt.): 47 x 47 x 150 mm  Dimensiones Mínimas (Anch. X Prof. X Alt.): 1,85 x 1,85 x 5,91 pulgadas Pesos Peso: 0,12 kg  Peso Del Embalaje: 0,13 kg  Peso Del Embalaje: 0,29 lb Compatibilidad  Compatibilidad Con Hardware: Impresoras HP Smart Tank serie 510, HP Smart Tank Plus serie 550, HP Smart Tank Plus serie 610  Aquellas impresoras que utilicen tinta de modelo GT51 o GT51XL han sido reemplazados por este modelo GT53, es totalmente compatible verificado por la marca.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1105163845",
    title: "Mouse Pad Gamer Hp Mp9040 De Goma L 400mm X 900mm X 3mm Negro",
    image: "http://http2.mlstatic.com/D_829026-MLA41162250935_032020-O.jpg",
    price: 4999,
    category: "MLA1716",
    stock: 1,
    sold: 500,
    description:
      "Es tan fácil deslizar el mouse. Con tu HP MP9040 podrás llenar la pantalla de tu computadora de clicks. Su elaborada superficie le dará precisión y comodidad a tus movimientos. Calidad en su confección Diseñada con excelente materia prima, tu almohadilla te dará una agradable sensación al tacto y evitará un gran desgaste en la base de tu mouse. Su confección hará que tu mano vuele por la superficie ya que es compatible para funcionar con todo tipo de sensores, inclusive algunos más antiguos.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1105197450",
    title: "Cargador Hp Pavilion Envy 14-b 14z-b 15-b 15t-b 19.5v 3.33a",
    image: "http://http2.mlstatic.com/D_708878-MLA53072412960_122022-O.jpg",
    price: 5400,
    category: "MLA3577",
    stock: 1,
    sold: 500,
    description:
      "Cargador de Notebook HP Voltaje: 19.5v Amperaje: 3.33a Potencia: 65w Pin: 4.5 * 3.0 SIN CABLE POWER Compatibles para los modelos: HP Pavilion Sleekbook 14-B, 14Z-B, 15-B, 15T-B Series HP Pavilion Chromebook 14-C Series HP ENVY Spectre XT Pro Ultrabook 13, 14, NV13, NV14 Series HP Spare 677770-003, 677770-001,677770- 002, 613149-003, 693715-001 Laptops HP Pavilion Sleekbook Series Ultraportable. HP ENVY Sleekbook 6-1000 Series- HP ENVY Sleekbook series. HP ENVY 4/6 Series Ultraportable Laptop Compatible con los números de parte: 15AC070TX709985-001709985-002709985-003709985-004709986-001709986-002709986-003709986-004709987-001709987-002709987-003710412-001710412-004710413-001710414-001714159-001714657-001740015-001740015-002740015-003741727-001758633-001A045R07DHA065R01DLA090A07DLAD9043-022G2ADP-45FE.BADP-90WH DEPA45-19-45PHSTNN-CA40HSTNN-DA13HSTNN-DA40HSTNN-LA15HSTNN-LA40PA-1450-36HEPA-1650-32HEPA-1650-34HEPA-1900-34HEPPP009CPPP012C-SPPP012D-S HP 256 G4 HP 256 G5 HP 340 G1, G3 HP 345 G1, G2 HP 350 G1, G2 HP 355 G1, G2 HP mt245 HP Chromebook 14-b000 - b099 HP Chromebook 14-c000",
    AdminUser: "NULL",
  },
  {
    id: "MLA1116993757",
    title:
      "Notebook Hp 15-dy2061la Plateada Natural 15.6 Intel Core I3 1125g4  8gb De Ram 256gb Ssd Intel",
    image: "http://http2.mlstatic.com/D_644602-MLA48643624987_122021-O.jpg",
    price: 385999,
    category: "MLA1652",
    stock: 50,
    sold: 250,
    description:
      'La notebook HP 15-DY2061LA es una solución tanto para trabajar y estudiar como para entretenerte. Al ser portátil, el escritorio dejará de ser tu único espacio de uso para abrirte las puertas a otros ambientes ya sea en tu casa o en la oficina. Pantalla con gran impacto visual Su pantalla de 15.6"" y 1366x768px de resolución te brindará colores más vivos y definidos. Tus películas y series preferidas cobrarán vida, ya que ganarán calidad y definición en cada detalle. Eficiencia a tu alcance Su procesador Intel Core i3 de 4 núcleos, está pensado para aquellas personas generadoras y consumidoras de contenidos. En base a esto, permite el desempeño necesario para la edición de fotografías o videos en programas básicos. Potente disco sólido El disco sólido de 256 GB hace que el equipo funcione a gran velocidad y por lo tanto te brinda mayor agilidad para operar con diversos programas. Un procesador exclusivo para los gráficos Su placa de video Intel UHD Graphics Xe G4 48EUs convierte a este dispositivo en una gran herramienta de trabajo para cualquier profesional del diseño. Te permitirá lograr una gran performance en todos tus juegos y en otras tareas cotidianas que impliquen procesamiento gráfico. Una batería de larga duración La batería de este equipo tiene una autonomía de alrededor de 11 horas. La duración varía según el uso, la configuración y otros factores, pero es ideal para quienes necesitan extender su jornada y seguir trabajando o estudiando con comodidad y sin cables.""}"',
    AdminUser: "NULL",
  },
  {
    id: "MLA1119716408",
    title: "Compu Pc Cpu Hp Compaq 6300 I5 3era 240gb Ssd 8gb Ram + Wifi",
    image: "http://http2.mlstatic.com/D_957667-MLA48859517110_012022-O.jpg",
    price: 108480,
    category: "MLA1649",
    stock: 1,
    sold: 25,
    description:
      "Compu Pc Cpu Desktop Hp Compaq 6300 SFF  Equipo reacondicionado CLASE A  Estéticamente muy bien cuidado y 100% funcional  Listas para usar *** INCLUYE ANTENA WIFI GRATIS *** Características:  Procesador: Intel Core i5 3ta Generación  Almacenamiento: 240GB SSD (disco sólido)  RAM: 8GB DDR3  Video integrado: Intel HD Graphics 2500 / 2GB  Puertos: VGA, USB, RJ-45, DisplayPort, Auriculares Contenido del paquete:  HP Compaq 6300 SFF  Cable de poder  Antena Wi-Fi IMPORTANTE  TODOS nuestros equipos tienen 1 año de garantía.  Windows 10 Pro 64 Bits y Paquete Office 2019.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1122243562",
    title: "Impresora A Color MultifunciÃ³n Hp Ink Tank 315 Negra 100v/240v",
    image: "http://http2.mlstatic.com/D_838858-MLA41730657807_052020-O.jpg",
    price: 140390,
    category: "MLA1676",
    stock: 1,
    sold: 100,
    description:
      "HP provee las impresoras más seguras del mundo. Con ellas, conseguirás proteger tu información, obtener lo máximo en tecnología y un rendimiento impresionante que se adaptará a cualquier reto que tengas. Sin dudas, esta máquina es ideal para cumplir, de forma eficiente, la meta que te propongas. Eficiencia y calidad Imprimí archivos, escaneá documentos y hacé todas las fotocopias que necesités con esta impresora multifunción HP, siempre lista para facilitar tu rutina de trabajo o estudio. Perfecta para tu hogar o la oficina Al ser a tinta te permitirá lograr impresiones de gran calidad con colores vivos y degradados suaves. Ocupa poco espacio y es fácil de manejar lo que la convierte en la opción ideal para cuestiones laborales, tareas escolares y requerimientos de la vida diaria.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1123750218",
    title: "Kit De Cartuchos De Tinta Hp 667 Tricolor + Negro Original",
    image: "http://http2.mlstatic.com/D_815409-MLA49128218407_022022-O.jpg",
    price: 25998,
    category: "MLA7415",
    stock: 500,
    sold: 500,
    description:
      "Kit De Cartuchos De Tinta Hp 667 Tricolor + Negro Original Imprima documentos con texto definido y colores vívidos gracias a los cartuchos de tinta original HP que están diseñados para brindar impresiones de calidad para su hogar, escuela o empresa pequeña. Gracias a los cartuchos a muy bajo precio, obtiene tinta original HP a un precio asequible. Confíe en cartuchos de tinta original HP para brindar un buen rendimiento de impresión. Ayude a garantizar las impresiones vívidas y definidas para el hogar, la escuela y el trabajo con cartuchos diseñados y probados con su impresora HP y diseñados para facilitar el uso. Los cartuchos originales HP que son ideales para su forma de vivir, trabajar e imprimir. ",
    AdminUser: "NULL",
  },
  {
    id: "MLA1128077288",
    title: "Drum Hp 104a W1104a Negro Original Neverstop 1200 1000 ",
    image: "http://http2.mlstatic.com/D_940664-MLA54822378134_042023-O.jpg",
    price: 74995,
    category: "MLA3560",
    stock: 1,
    sold: 250,
    description:
      "Drum Original HP 104A (W1104A) - Para Impresora HP Neverstop 1000A, 1000W, 1200A, 1200W, 1200NW - Rendimiento 20,000 Páginas - Producto Original E S P E C I F I C A C I O N E S  Peso y dimensiones - Peso 1.58 kg - Altura 137.3 mm - Ancho 324.5 mm - Profundidad 256.3 mm - Altura de la caja 191 mm - Ancho de la caja 387 mm Condiciones ambientales - Intervalo de humedad relativa para funcionamiento 20 - 80% - Intervalo de temperatura de almacenaje -20 - 40 c - Intervalo de temperatura operativa 0 -35 c - Intervalo de humedad relativa durante almacenaje 10 - 90% Empaquetado - Peso del paquete 2.1 kg - Profundidad de la caja 296 mm - Contenido del embalaje - Cantidad por paquete 1 pieza(s) Otras características - Compatibilidad HP Neverstop Laser 1000, 1001, 1020, 1200, 1201, 1202 - Tipo Original - Tecnología de impresión Impresión láser - Colores de impresión Negro - País de origen China - Marca compatible HP - Código OEM W1104A - Rendimiento 20000 páginas - Black toner cartridges quantity 1 - Unidad de tambor incorporada",
    AdminUser: "NULL",
  },
  {
    id: "MLA1136259403",
    title:
      "Impresora A Color MultifunciÃ³n Hp Smart Tank 530 Con Wifi Negra 200v - 240v",
    image: "http://http2.mlstatic.com/D_993309-MLA45074625714_032021-O.jpg",
    price: 179400,
    category: "MLA1676",
    stock: 1,
    sold: 50,
    description:
      "HP provee las impresoras más seguras del mundo. Con ellas, conseguirás proteger tu información, obtener lo máximo en tecnología y un rendimiento impresionante que se adaptará a cualquier reto que tengas. Sin dudas, esta máquina es ideal para cumplir, de forma eficiente, la meta que te propongas. Eficiencia y calidad Imprimí archivos, escaneá documentos y hacé todas las fotocopias que necesités con esta impresora multifunción HP, siempre lista para facilitar tu rutina de trabajo o estudio. Perfecta para tu hogar o la oficina Al ser a tinta te permitirá lograr impresiones de gran calidad con colores vivos y degradados suaves. Ocupa poco espacio y es fácil de manejar lo que la convierte en la opción ideal para cuestiones laborales, tareas escolares y requerimientos de la vida diaria. Conectividad móvil Ahora podés imprimir fácilmente desde tu celular o tablet sin importar en donde te encuentres y sin la asistencia de una computadora. Disfrutá de sus soluciones de impresión móvil, utilizá la que más te guste y tené tus documentos en solo segundos.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1140365970",
    title:
      "Notebook Hp 14-dq2029la Plata Natural 14  Intel Core I5 1135g7  8gb De Ram 256gb Ssd Intel Iris Xe Graphics G7 80eus 1366x768px Windows 10 Home",
    image: "http://http2.mlstatic.com/D_822203-MLA52221738161_102022-O.jpg",
    price: 439999,
    category: "MLA1652",
    stock: 1,
    sold: 25,
    description:
      "La notebook HP 14-dq2029la es una solución tanto para trabajar y estudiar como para entretenerte. Al ser portátil, el escritorio dejará de ser tu único espacio de uso para abrirte las puertas a otros ambientes ya sea en tu casa o en la oficina. Pantalla con gran impacto visual Su pantalla de 14 y 1366x768px de resolución te brindará colores más vivos y definidos. Tus películas y series preferidas cobrarán vida, ya que ganarán calidad y definición en cada detalle. Eficiencia a tu alcance Su procesador Intel Core i5 de 4 núcleos, está pensado para aquellas personas generadoras y consumidoras de contenidos. Con esta unidad central, la máquina llevará a cabo varios procesos de forma simultánea, desde edición de videos hasta retoques fotográficos con programas profesionales. Potente disco sólido El disco sólido de 256 GB hace que el equipo funcione a gran velocidad y por lo tanto te brinda mayor agilidad para operar con diversos programas. Un procesador exclusivo para los gráficos Su placa de video Intel Iris Xe Graphics G7 80EUs convierte a este dispositivo en una gran herramienta de trabajo para cualquier profesional del diseño. Te permitirá lograr una gran performance en todos tus juegos y en otras tareas cotidianas que impliquen procesamiento gráfico. Una batería de larga duración La batería de este equipo tiene una autonomía de alrededor de 11.3 horas. La duración varía según el uso, la configuración y otros factores, pero es ideal para quienes necesitan extender su jornada y seguir trabajando o estudiando con comodidad y sin cables.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1141072809",
    title: "Notebook Hp Probook 440 G8 I7 1165g7 16gb Ssd 512gb W10 Pro ",
    image: "http://http2.mlstatic.com/D_742164-MLA50074284331_052022-O.jpg",
    price: 772825.35,
    category: "MLA1652",
    stock: 1,
    sold: 25,
    description:
      "Un nuevo diseño que se adapta a los estilos de trabajo modernos El PC portátil HP ProBook 440, que presenta un diseño nuevo y compacto, brinda el rendimiento, la seguridad y la durabilidad que buscan los profesionales de empresas en expansión. El chasis compacto, ligero y delgado con componentes de aluminio es fácil de transportar de un lugar a otro. Disfrute de una relación de pantalla y cuerpo de más del 87 % y un teclado receptivo y silencioso. Protección de seguridad de múltiples capas HP Wolf Security for Business crea una defensa resistente de ejecución obligatoria en el hardware que se encuentra siempre activa. Desde el BIOS hasta el navegador, en el mismo sistema operativo y en niveles superiores e inferiores a este, estas soluciones en constante evolución ayudan a proteger su equipo de las amenazas modernas. Potencia hecha para durar El HP ProBook 440 va equipado con el último procesador de cuatro núcleos de Intel, con la innovadora tarjeta gráfica Intel Iris Xe y con una memoria SODIMM de dos canales rápida y ampliable . Además, la batería de larga duración y la unidad de estado sólido de alta velocidad mejoran su rendimiento. El chasis ligero con componentes de aluminio le da un aspecto elegante.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1146215086",
    title: "Pc Hp Dc5100 1 Gb Ram Sin Disco Excelente Estado",
    image: "http://http2.mlstatic.com/D_945409-MLA50661561098_072022-O.jpg",
    price: 24900,
    category: "MLA1649",
    stock: 50,
    sold: 4,
    description:
      "Un nuevo diseño que se adapta a los estilos de trabajo modernos El PC portátil HP ProBook 440, que presenta un diseño nuevo y compacto, brinda el rendimiento, la seguridad y la durabilidad que buscan los profesionales de empresas en expansión. El chasis compacto, ligero y delgado con componentes de aluminio es fácil de transportar de un lugar a otro. Disfrute de una relación de pantalla y cuerpo de más del 87 % y un teclado receptivo y silencioso. Protección de seguridad de múltiples capas HP Wolf Security for Business crea una defensa resistente de ejecución obligatoria en el hardware que se encuentra siempre activa. Desde el BIOS hasta el navegador, en el mismo sistema operativo y en niveles superiores e inferiores a este, estas soluciones en constante evolución ayudan a proteger su equipo de las amenazas modernas. Potencia hecha para durar El HP ProBook 440 va equipado con el último procesador de cuatro núcleos de Intel, con la innovadora tarjeta gráfica Intel Iris Xe y con una memoria SODIMM de dos canales rápida y ampliable . Además, la batería de larga duración y la unidad de estado sólido de alta velocidad mejoran su rendimiento. El chasis ligero con componentes de aluminio le da un aspecto elegante.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1146953786",
    title: "Pc Hp Dc5100 2 Gb Ram Disco De 80 Gb ",
    image: "http://http2.mlstatic.com/D_945409-MLA50661561098_072022-O.jpg",
    price: 29900,
    category: "MLA1649",
    stock: 50,
    sold: 5,
    description:
      "Especificaciones Opciones Procesador Fabricante de procesador *Intel Modelo del procesador *630 Familia de procesador *Intel® Pentium® 4 Número de núcleos de procesador1 Frecuencia del procesador *3 GHz Socket de procesadorLGA 775 (Socket T) Caché del procesador2 MB Tipo de cache en procesadorL2 Número de hilos de ejecución2 FSB, Front side bus800 MHz Tipos de busFSB Paridad FSBNo Litografía del procesador90 nm Modo de procesador operativo64 bits Serie del procesadorIntel Pentium 4 600 Series supporting Hyper-Threading Technology Procesador nombre en clavePrescott Potencia de diseño térmico (TDP)84 W Tcase66,6 °C Número de Transistores Die de Procesador169 M Tamaño de die de procesamiento135 mm² Ratio bus/core15 ECC que admite el procesadorNo Memoria Memoria interna *0,5 GB Memoria interna máxima *4 GB Tipo de memoria internaDDR2-SDRAM Medios de almacenaje Tarjeta de lectura integradaNo Gráficos Adaptador gráfico incorporado *No Conexión Ethernet *Yes Wifi *No Puertos e Interfaces",
    AdminUser: "NULL",
  },
  {
    id: "MLA1148951115",
    title: "Pc Hp Sempron  2 Gb De Ram Disco De 160 Gb Win 7 Officce",
    image: "http://http2.mlstatic.com/D_864216-MLA54872409002_042023-O.jpg",
    price: 34900,
    category: "MLA1649",
    stock: 150,
    sold: 5,
    description:
      "PC HP AMD SEMPRON 3000+ 1.60 GHZ DC PRECIO MAS BAJO 2 GB DE RAM DDR 2 DISCO DE 160 GB LECTORA DE CD/DVD WINDOWS 7 OFFICCE OPCIONAL WIFFI $1500 - Equipos de linea corporativa que multinacionales usaron y renovaron porque se les exige. - Comparables y muchas veces mejores que equipos nuevos pensados para USUARIOS o PYMES, pero economicamente mas accesible. - Al equipo se le realizaron los siguientes procedimientos: borrado de datos, limpieza del equipo y verificación de funcionalidad. rabajamos con computadoras originales Dell y Hp, marca lideres en ordenadores personales. Equipos con mayor eficiencia y durababilidad que los genericos. - Ideal para comercios, oficinas o uso hogareño por su rendimiento y gran durabilidad. Puede estar horas prendidas sin afectar su rendimiento. - Realizamos un exhaustivo control de calidad en el reacondicionamiento del equipo. Damos una garantia de 12 meses que cubre cualquier inconveniente del equipo a nivel hardware. - Incluye sistema operativo, todos los programas mas utilizados Lista para enchufar y disfrutarla!",
    AdminUser: "NULL",
  },
  {
    id: "MLA1157327769",
    title: "Cargador Hp 19 5v 2.31a 45w Pavilion 14 15 Envy 4 6 M6 Orig",
    image: "http://http2.mlstatic.com/D_688903-MLA51259743992_082022-O.jpg",
    price: 6999,
    category: "MLA3577",
    stock: 150,
    sold: 250,
    description:
      "Cargador Original Notebook Hp 19,5v 2.31A 45W Pavilion 14 15 Envy 4 6 M6 Original ***IMPORTANTE: En caso de NO tener STOCK de 45w, se entregara de 65W, ya que es totalmente compatible con la versión y potencia de 45w.*** NO INCLUYE CABLE POWER! Características: Entrada: 100-240v, 50-60 hz Salida: 19.5v 2.31a Potencia: 45W Ficha: 4.5mm x 3.0 mm. Tipo: Original Garantía: 2 meses MODELOS COMPATIBLES: ***( CTRL + F para buscar tú modelo)*** HP Pavilion Sleekbook 14-B, 14Z-B, 15-B, 15T-B Series HP Pavilion Chromebook 14-C Series HP ENVY Spectre XT Pro Ultrabook 13, 14, NV13, NV14 Series HP Spare 677770-003, 677770-001,677770- 002, 613149-003, 693715-001 Laptops HP Pavilion Sleekbook Series Ultraportable. HP ENVY Sleekbook 6-1000 Series- HP ENVY Sleekbook series. HP ENVY 4/6 Series Ultraportable Laptop NO INCLUYE CABLE POWER! Somos Distribuidores Oficiales de todas las Marcas. que Trabajamos, Garantías Oficiales en Argentina. HACEMOS FACTURA C UNICAMENTE!!! Estamos a pocas cuadras de la facultad de ciencias sociales del barrio Monserrat y de la estación de subte linea E. Atendemos de Lunes a Viernes de corrido de 11 a 18 hs, sábados de 11hs a 14hs. Domingos y feriados, cerrado. Sábados, Domingos y feriados, cerrado.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1163264509",
    title: "Hp Deskjet Ink Advantage 2375 - Blanco/verde - 100v/240v",
    image: "http://http2.mlstatic.com/D_885700-MLA44482330203_012021-O.jpg",
    price: 45927.25,
    category: "MLA1676",
    stock: 1,
    sold: 250,
    description:
      "HP provee las impresoras más seguras del mundo. Con ellas, conseguirás proteger tu información, obtener lo máximo en tecnología y un rendimiento impresionante que se adaptará a cualquier reto que tengas. Sin dudas, esta máquina es ideal para cumplir, de forma eficiente, la meta que te propongas. Eficiencia y calidad Imprimí archivos, escaneá documentos y hacé todas las fotocopias que necesités con esta impresora multifunción HP, siempre lista para facilitar tu rutina de trabajo o estudio. Perfecta para tu hogar o la oficina Al ser a tinta te permitirá lograr impresiones de gran calidad con colores vivos y degradados suaves. Ocupa poco espacio y es fácil de manejar lo que la convierte en la opción ideal para cuestiones laborales, tareas escolares y requerimientos de la vida diaria.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1177146821",
    title:
      "Impresora A Color Multifuncional Hp Smart Tank 515 Con Wifi Negra 100v/240v",
    image: "http://http2.mlstatic.com/D_962058-MLA41235635226_032020-O.jpg",
    price: 165999,
    category: "MLA1676",
    stock: 1,
    sold: 5,
    description:
      "HP provee las impresoras más seguras del mundo. Con ellas, conseguirás proteger tu información, obtener lo máximo en tecnología y un rendimiento impresionante que se adaptará a cualquier reto que tengas. Sin dudas, esta máquina es ideal para cumplir, de forma eficiente, la meta que te propongas. Eficiencia y calidad Imprimí archivos, escaneá documentos y hacé todas las fotocopias que necesités con esta impresora multifunción HP, siempre lista para facilitar tu rutina de trabajo o estudio. Perfecta para tu hogar o la oficina Al ser a tinta te permitirá lograr impresiones de gran calidad con colores vivos y degradados suaves. Ocupa poco espacio y es fácil de manejar lo que la convierte en la opción ideal para cuestiones laborales, tareas escolares y requerimientos de la vida diaria. Conectividad móvil Ahora podés imprimir fácilmente desde tu celular o tablet sin importar en donde te encuentres y sin la asistencia de una computadora. Disfrutá de sus soluciones de impresión móvil, utilizá la que más te guste y tené tus documentos en solo segundos.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1287639452",
    title: "Mini Hp Pc 260 G4 Celeron 5205u 4gb 1tb Windows 10 Hdmi ",
    image: "http://http2.mlstatic.com/D_644326-MLA46506816458_062021-O.jpg",
    price: 220784.85,
    category: "MLA1649",
    stock: 1,
    sold: 5,
    description:
      "LOS PRODUCTOS CON GARANTÍA DESDE LA FECHA DE COMPRA ES CUBIERTA ÚNICAMENTE POR DESPERFECTOS DE FABRICA. NO SE ACEPTAN COMPONENTES QUEMADOS, NI PRODUCTOS GOLPEADOS O CON SIGNOS DE MALTRATO Y MAL USO. SE DEBERÁ ENTREGAR EN LAS MISMAS CONDICIONES QUE FUE ENTREGADO, EN PERFECTO ESTADO Y CON SU EMBALAJE ORIGINAL Y COMPLETO. LA MERCADERÍA EN GARANTÍA SERÁ TOMADA A CONDICIÓN HASTA SER REVISADA POR NUESTRO SERVICIO TÉCNICO PUDIENDO TOMARSE EL MISMO HASTA 7 DÍAS HÁBILES.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1287990482",
    title: "Notebook Hp 15.6 Full Hd  Amd Ryzen 5 12gb Ssd 256gb Ram W11",
    image: "http://http2.mlstatic.com/D_999574-MLA50433188313_062022-O.jpg",
    price: 470000,
    category: "MLA1652",
    stock: 1,
    sold: 0,
    description:
      "La notebook HP 15-ef2013dx es una solución tanto para trabajar y estudiar como para entretenerte. Al ser portátil, el escritorio dejará de ser tu único espacio de uso para abrirte las puertas a otros ambientes ya sea en tu casa o en la oficina. Eficiencia a tu alcance Su procesador AMD Ryzen 5, te permitirá ejecutar programas variados y procesos indispensables para desenvolverte en el día a día, ya sea en tu trabajo o en los momentos de ocio en tu hogar. Potente disco sólido El disco sólido de 256 GB hace que el equipo funcione a gran velocidad y por lo tanto te brinda mayor agilidad para operar con diversos programas.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1361660897",
    title:
      "Notebook Hp 15-ef2514la Plata 15.6 Amd Ryzen 7 5700u  8gb De Ram 512gb Ssd Amd Radeon Rx Vega 8",
    image: "http://http2.mlstatic.com/D_982323-MLA51606812711_092022-O.jpg",
    price: 524999,
    category: "MLA1652",
    stock: 50,
    sold: 250,
    description:
      'La notebook HP 15-ef2514la es una solución tanto para trabajar y estudiar como para entretenerte. Al ser portátil, el escritorio dejará de ser tu único espacio de uso para abrirte las puertas a otros ambientes ya sea en tu casa o en la oficina. Pantalla con gran impacto visual Su pantalla de 15.6"" y 1366x768px de resolución te brindará colores más vivos y definidos. Tus películas y series preferidas cobrarán vida, ya que ganarán calidad y definición en cada detalle. Eficiencia a tu alcance Su procesador AMD Ryzen 7 de 8 núcleos, te permitirá ejecutar programas variados y procesos indispensables para desenvolverte en el día a día, ya sea en tu trabajo o en los momentos de ocio en tu hogar. Potente disco sólido El disco sólido de 512 GB hace que el equipo funcione a gran velocidad y por lo tanto te brinda mayor agilidad para operar con diversos programas. Un procesador exclusivo para los gráficos Su placa de video AMD Radeon RX Vega 8 (Ryzen 4000/5000) convierte a este dispositivo en una gran herramienta de trabajo para cualquier profesional del diseño. Te permitirá lograr una gran performance en todos tus juegos y en otras tareas cotidianas que impliquen procesamiento gráfico. Una batería que acompaña tu jornada La batería de este equipo tiene una autonomía de alrededor de 10 horas. La duración varía según el uso, la configuración y otros factores, pero vas a poder usarla durante varias horas sin depender de los enchufes.',
    AdminUser: "NULL",
  },
  {
    id: "MLA1362118921",
    title: "Pc Cpu Completa Hp  Core I3 16 Gb Ddr3  Ssd 240gb Monitor 17",
    image: "http://http2.mlstatic.com/D_643602-MLA54967318493_042023-O.jpg",
    price: 149990,
    category: "MLA1649",
    stock: 200,
    sold: 4,
    description:
      "Pc Cpu Completa HP Lenovo dell segun stok Core I3 4160 4TA GENERACION 16 Gb ddr3 ssd 240 Gb Monitor 17 teclado mouse ,wiffi ,windows 10 ,officce todos los cables lista para usar Excelente estado.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1363585333",
    title: "Auriculares Hp Dhe-8010 Gamer Oficina Con Luces Y Microfono Negro",
    image: "http://http2.mlstatic.com/D_685766-MLA53985487971_022023-O.jpg",
    price: 7749,
    category: "MLA6049",
    stock: 1,
    sold: 0,
    description:
      "La nueva línea de HP llegó para quedarse, tecnología de primer nivel para gaming y oficinas Exclusivamente para PC Headphone USB + 3,5mm para mic + 3,5mm para audio Características: Stereo Deep Bass con efecto Surround  Luces LED en laterales  Cable de 2m  Ajuste de volumen On-ear  Micrófono omnidireccional ajustable Potencia: 15mW S Frecuencia: 20Hz - 20KHz Sensibilidad: 100dB ± 3dB.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1366062513",
    title:
      "Impresora A Color MultifunciÃ³n Hp Smart Tank 720 Con Wifi Blanca 100v/240v",
    image: "http://http2.mlstatic.com/D_979306-MLA52224143087_102022-O.jpg",
    price: 185000,
    category: "MLA1676",
    stock: 1,
    sold: 5,
    description:
      "HP provee las impresoras más seguras del mundo. Con ellas, conseguirás proteger tu información, obtener lo máximo en tecnología y un rendimiento impresionante que se adaptará a cualquier reto que tengas. Sin dudas, esta máquina es ideal para cumplir, de forma eficiente, la meta que te propongas. Eficiencia y calidad Imprimí archivos, escaneá documentos y hacé todas las fotocopias que necesités con esta impresora multifunción HP, siempre lista para facilitar tu rutina de trabajo o estudio. Perfecta para tu hogar o la oficina Al ser a tinta te permitirá lograr impresiones de gran calidad con colores vivos y degradados suaves. Ocupa poco espacio y es fácil de manejar lo que la convierte en la opción ideal para cuestiones laborales, tareas escolares y requerimientos de la vida diaria. Conectividad móvil Ahora podés imprimir fácilmente desde tu celular o tablet sin importar en donde te encuentres y sin la asistencia de una computadora. Disfrutá de sus soluciones de impresión móvil, utilizá la que más te guste y tené tus documentos en solo segundos.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1372536879",
    title:
      "Notebook Hp 14-dq0515la Negra 14  Intel Celeron N4120  4gb De Ram 256gb Ssd Intel Uhd Graphics 600 1366x768px Windows 11 Home",
    image: "http://http2.mlstatic.com/D_846400-MLA69387258943_052023-O.jpg",
    price: 229999,
    category: "MLA1652",
    stock: 50,
    sold: 25,
    description:
      "La notebook HP 14-dq0515la es una solución tanto para trabajar y estudiar como para entretenerte. Al ser portátil, el escritorio dejará de ser tu único espacio de uso para abrirte las puertas a otros ambientes ya sea en tu casa o en la oficina. Pantalla con gran impacto visual Su pantalla de 14 y 1366x768px de resolución te brindará colores más vivos y definidos. Tus películas y series preferidas cobrarán vida, ya que ganarán calidad y definición en cada detalle. Eficiencia a tu alcance Con su procesador Intel Celeron de 4 núcleos, lograrás el desempeño que necesitás para navegar y trabajar. Podrás usar los programas más esenciales, llevar a cabo tus tareas y organizar tu vida diaria.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1374179070",
    title:
      "Notebook Hp Pavilion 15-dy2791wm Plateada Intel Core I3 1115g4  8gb De Ram 256gb Ssd Intel Uhd Graphics 60 Hz 1366x768px Windows 11 Home",
    image: "http://http2.mlstatic.com/D_960011-MLA52697243841_122022-O.jpg",
    price: 460938,
    category: "MLA1652",
    stock: 1,
    sold: 0,
    description:
      "La notebook HP Pavilion 15-dy2791wm es una solución tanto para trabajar y estudiar como para entretenerte. Al ser portátil, el escritorio dejará de ser tu único espacio de uso para abrirte las puertas a otros ambientes ya sea en tu casa o en la oficina. Eficiencia a tu alcance Su procesador Intel Core i3 de 2 núcleos, está pensado para aquellas personas generadoras y consumidoras de contenidos. En base a esto, permite el desempeño necesario para la edición de fotografías o videos en programas básicos. Potente disco sólido El disco sólido de 256 GB hace que el equipo funcione a gran velocidad y por lo tanto te brinda mayor agilidad para operar con diversos programas. Un procesador exclusivo para los gráficos Su placa de video Intel UHD Graphics convierte a este dispositivo en una gran herramienta de trabajo para cualquier profesional del diseño. Te permitirá lograr una gran performance en todos tus juegos y en otras tareas cotidianas que impliquen procesamiento gráfico.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1374274603",
    title:
      "Notebook Hp Victus 15-fa0031dx 8gb Ram 512gb Ssd Intel Core I5 Nvidia Geforce Gtx 1650 4gb Gddr6 15.6  Fhd 144hz Windows 11 ",
    image: "http://http2.mlstatic.com/D_715158-MLA51949377565_102022-O.jpg",
    price: 470000,
    category: "MLA1652",
    stock: 1,
    sold: 4,
    description:
      'La notebook para juegos Victus 15-FA0031DX de 15.1 pulgadas de HP tiene lo que necesita para jugar, incluido un procesador potente, excelentes gráficos, un sistema de enfriamiento mejorado y una pantalla de alta resolución. Impulsado por un procesador Intel Core i5-12450H de 8 núcleos y 8 GB de memoria RAM DDR4 de 3200 MHz. Experimente el potente rendimiento de gráficos de la galardonada arquitectura NVIDIA Turing con la tarjeta gráfica GeForce GTX Serie 16. Además, para el almacenamiento de sus archivos, incorpora un SSD M.2 NVMe de 512 GB. Pantalla: IPS de 15.6"" con resolución Full HD 1920 x 1080p a 144Hz Procesador: Intel Core i5-12450H Octa-Core 2.0 - 4.4 GHz Memoria RAM: 8 GB DDR4 Memoria de almacenamiento: SSD M.2 NVMe de 512 GB Gráficos: NVIDIA Geforce GTX 1650 de 4 GB GDDR6 Sistema operativo: Windows 11 Home.',
    AdminUser: "NULL",
  },
  {
    id: "MLA1379159681",
    title:
      "Notebook Hp Amd Ryzen 5 5500u 8gb Ram 256gb Windows 11 Home 15.6 Pulgadas Azul Full Hd",
    image: "http://http2.mlstatic.com/D_998705-MLA53303083918_012023-O.jpg",
    price: 423990,
    category: "MLA1652",
    stock: 1,
    sold: 0,
    description:
      'La notebook HP 15-EF2729WM es una solución tanto para trabajar y estudiar como para entretenerte. Al ser portátil, el escritorio dejará de ser tu único espacio de uso para abrirte las puertas a otros ambientes ya sea en tu casa o en la oficina. Pantalla con gran impacto visual Su pantalla de 15,6"" FHD te brindará colores más vivos y definidos. Tus películas y series preferidas cobrarán vida, ya que ganarán calidad y definición en cada detalle. Eficiencia a tu alcance Su procesador RYZEN 5 5500U, está pensado para aquellas personas generadoras y consumidoras de contenidos. Con esta unidad central, la máquina llevará a cabo varios procesos de forma simultánea, desde edición de videos hasta retoques fotográficos con programas profesionales. Potente disco sólido El disco sólido de 256 GB hace que el equipo funcione a gran velocidad y por lo tanto te brinda mayor agilidad para operar con diversos programas. Una batería que acompaña tu jornada La duración varía según el uso, la configuración y otros factores, pero vas a poder usarla durante varias horas sin depender de los enchufes.',
    AdminUser: "NULL",
  },
  {
    id: "MLA1389500740",
    title: "Cpu Hp Compaq I3 3220 8gb - Hdd 500 + Monitor 19 ",
    image: "http://http2.mlstatic.com/D_701131-MLA69317976505_052023-O.jpg",
    price: 90900,
    category: "MLA1649",
    stock: 1,
    sold: 4,
    description:
      'CPU HP COMPAQ PRO 6300 SMALL FORM FACTOR I3 3220 3era Generación 8GB de RAM y Disco Rígido de 500gb HDD + Monitor 19"" incluye sus cables y periféricos + Windows pro 10 de Prueba',
    AdminUser: "NULL",
  },
  {
    id: "MLA1393681384",
    title: "Notebook Hp 15-dy5001la Intel I5 1235u 8gb 512gb M.2 Win 11",
    image: "http://http2.mlstatic.com/D_605447-MLA54849416205_042023-O.jpg",
    price: 493999,
    category: "MLA1652",
    stock: 50,
    sold: 500,
    description:
      "Notebook HP 15-dy5001la - 767U2LA Una laptop liviana para trabajar o jugar, dondequiera que la necesites. Realiza todo lo que necesitas hacer, todo el día y dondequiera que prefieras, gracias a la laptop HP de 15,6 pulgadas que tiene un diseño liviano y una batería de larga duración1. Disfruta de la comodidad que te ofrece la pantalla libre de parpadeo2 y obtén desempeño confiable gracias al procesador Intel Core 3. Además, esta laptop fue fabricada teniendo en cuenta el planeta y cuenta con el registro EPEAT Silver4 y la certificación ENERGY STAR. Mantente productivo y entretenido desde cualquier lugar gracias a la batería de larga duración y la pantalla con microbordes. Especificaciones - Sistema operativo: Windows 11 Home Single Language - Familia del procesador: Procesador Intel Core i5 de 12. generación - Procesador: Intel Core i5-1235U (hasta 4,4 GHz con tecnología Intel Turbo Boost, 12 MB de caché L3, 10 núcleos y 12 subprocesos)",
    AdminUser: "NULL",
  },
  {
    id: "MLA1395065176",
    title: "Pc Cpu Completa Hp  Core I3 16 Gb Ssd 240 Gb Monitor 19",
    image: "http://http2.mlstatic.com/D_953894-MLA70480691914_072023-O.jpg",
    price: 149990,
    category: "MLA1649",
    stock: 500,
    sold: 5,
    description:
      "Pc Cpu Completa HP-dell -lenovo segun stock Core I3 16 Gb SSD 240 Gb Monitor 19 teclado mouse ,windows 10 ,officce todos los cables lista para usar ¡EQUIPO REACONDICIONADO EN EXCELENTE ESTADO! 12 MESES DE GARANTÍA",
    AdminUser: "NULL",
  },
  {
    id: "MLA1399975722",
    title: "Hp M22f 21.5   - Negro/plata - 100v/240v",
    image: "http://http2.mlstatic.com/D_665797-MLA50596544390_072022-O.jpg",
    price: 67999,
    category: "MLA14407",
    stock: 1,
    sold: 200,
    description:
      "La visión de HP es crear tecnologías que mejoren ampliamente la vida de todas las personas del mundo. La empresa trabaja en la invención y el diseño de productos que brinden experiencias asombrosas. Tener un monitor HP es disfrutar de la alta calidad e innovación que ofrece la marca. Un monitor a tu medida Gracias a su pantalla LCD vas a obtener gráficas con gran nitidez, colores vivos y atractivos. Una experiencia visual de calidad Este monitor de 21.5 te va a resultar cómodo para estudiar, trabajar o ver una película en tus tiempos de ocio. Asimismo, su resolución de 1920 x 1080 te permite disfrutar de momentos únicos gracias a una imagen de alta fidelidad. Una de sus virtudes es que posee pantalla antirreflejo, de esta manera no verás reflejado lo que está detrás de vos y vas a evitar forzar tu vista para enfocar el contenido. Su tiempo de respuesta de 5 ms lo hace ideal para gamers y cinéfilos porque es capaz de mostrar imágenes en movimiento sin halos o bordes borrosos.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1408996188",
    title: "Mouse Pad Gamer TamaÃ±o Medio 35x24 Hp Mp3524 Gaming",
    image: "http://http2.mlstatic.com/D_736256-MLU69187807570_052023-O.jpg",
    price: 1950,
    category: "MLA1716",
    stock: 1,
    sold: 5,
    description:
      "Es tan fácil deslizar el mouse. Con tu HP MP3524 podrás llenar la pantalla de tu ordenador de clicks. Su elaborada superficie le dará precisión y comodidad a tus movimientos. Calidad en su confección Diseñada con materiales de calidad, tu almohadilla de goma te dará una agradable sensación al tacto y evitará un gran desgaste en la base de tu mouse. Este tipo de opción es ideal para gamers ya que reparte la presión de manera simétrica, conservando un nivel de precisión adecuado.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1417819154",
    title: "Impresora Todo En Uno Hp Smart Tank 580 Multifuncion Wifi",
    image: "http://http2.mlstatic.com/D_739566-MLU69348300209_052023-O.jpg",
    price: 166999,
    category: "MLA1676",
    stock: 50,
    sold: 150,
    description:
      "Impresora Todo-en-Uno HP Smart Tank 580 - 1F3Y2A Intuitivamente inteligente. Ligera de precio. Disfrute de confiabilidad diaria con la impresora HP Smart Tank 580 Todo-en-Uno que ofrece la calidad HP que usted espera y ahorros sorprendentes. Especificaciones - Velocidad de impresión: Negro: Hasta 12 cpm; Color: Hasta 5 cpm - Resolución de impresión: Negro (óptimo): Hasta 1200 x 1200 ppp de reproducción; Color (óptimo): Impresión en color de hasta 4800 x 1200 ppp optimizados (cuando se imprime desde una computadora y hay 1200 ppp de entrada) - Resolución de escaneo: Hardware: hasta 1200 x 1200 ppp; Óptico: hasta 1200 ppp - Resolución de copia: Negro (texto y gráficos): hasta 1,200 ppp; Color (texto y gráficos): hasta 1200 x 1200 ppp con velocidad reducida - Conectividad estándar: 1 Hi-Speed USB 2.0 (dispositivo); 1 Bluetooth de bajo consumo de energía; 1 Wi-Fi 802.11b/g/n; 1 Wi-Fi Direct - Capacidad de impresión móvil: Aplicación HP Smart; Apple AirPrint; Servicios de impresión Mopria; - Complemento de servicio de impresión HP (impresión Android); Impresión Wi-Fi Direct - Ciclo de trabajo: Mensual (carta): hasta 3000 páginas - Pantalla: Pantalla LCD de 33 segmentos + ícono de 1,2 - Manejo del papel: Bandeja de entrada de 100 hojas; - Bandeja salida de 30 hojas Valor del depósito inteligente - Hasta 12.000 páginas en negro o 6000 páginas en color de tinta le permiten seguir imprimiendo a una fracción del costo - Ahorre energía con la tecnología HP Auto-On/Auto-Off.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1420557236",
    title:
      "Notebook Hp Pavilion 13-bb0003la Plata Natural 13.3  Intel Core I5 1135g7  8gb De Ram 256gb Ssd 16gb Optane Intel",
    image: "http://http2.mlstatic.com/D_759223-MLA48455080889_122021-O.jpg",
    price: 654999,
    category: "MLA1652",
    stock: 1,
    sold: 0,
    description:
      'La notebook HP Pavilion 13-bb0003la es una solución tanto para trabajar y estudiar como para entretenerte. Al ser portátil, el escritorio dejará de ser tu único espacio de uso para abrirte las puertas a otros ambientes ya sea en tu casa o en la oficina. Pantalla con gran impacto visual Su pantalla de 13.3"" y 1920x1080px de resolución te brindará colores más vivos y definidos. Tus películas y series preferidas cobrarán vida, ya que ganarán calidad y definición en cada detalle. Eficiencia a tu alcance Su procesador Intel Core i5 de 4 núcleos, está pensado para aquellas personas generadoras y consumidoras de contenidos. Con esta unidad central, la máquina llevará a cabo varios procesos de forma simultánea, desde edición de videos hasta retoques fotográficos con programas profesionales. Potente disco sólido El disco sólido de 256 GB hace que el equipo funcione a gran velocidad y por lo tanto te brinda mayor agilidad para operar con diversos programas. Un procesador exclusivo para los gráficos Su placa de video Intel Iris Xe Graphics G7 80EUs convierte a este dispositivo en una gran herramienta de trabajo para cualquier profesional del diseño. Te permitirá lograr una gran performance en todos tus juegos y en otras tareas cotidianas que impliquen procesamiento gráfico. Una batería que acompaña tu jornada La batería de este equipo tiene una autonomía de alrededor de 9 horas. La duración varía según el uso, la configuración y otros factores, pero vas a poder usarla durante varias horas sin depender de los enchufes.',
    AdminUser: "NULL",
  },
  {
    id: "MLA1423075844",
    title:
      "Notebook Hp 15z-ef2000 Amd Ryzen 5 8gb De Ram 256gb Ssd 60 Hz 1920x1080px Windows 11 Home",
    image: "http://http2.mlstatic.com/D_920024-MLA69439614563_052023-O.jpg",
    price: 396039,
    category: "MLA1652",
    stock: 1,
    sold: 5,
    description:
      "La notebook HP 15z-EF2000 es una solución tanto para trabajar y estudiar como para entretenerte. Al ser portátil, el escritorio dejará de ser tu único espacio de uso para abrirte las puertas a otros ambientes ya sea en tu casa o en la oficina. Eficiencia a tu alcance Su procesador AMD Ryzen 5, te permitirá ejecutar programas variados y procesos indispensables para desenvolverte en el día a día, ya sea en tu trabajo o en los momentos de ocio en tu hogar. Potente disco sólido El disco sólido de 256 GB hace que el equipo funcione a gran velocidad y por lo tanto te brinda mayor agilidad para operar con diversos programas.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1437467356",
    title:
      "Impresora Simple FunciÃ³n Hp Laser 107w Con Wifi Gris Y Negra 220v - 240v 4zb78a",
    image: "http://http2.mlstatic.com/D_611622-MLA50584024225_072022-O.jpg",
    price: 160000,
    category: "MLA1676",
    stock: 1,
    sold: 2,
    description:
      "HP provee las impresoras más seguras del mundo. Con ellas, conseguirás proteger tu información, obtener lo máximo en tecnología y un rendimiento impresionante que se adaptará a cualquier reto que tengas. Sin dudas, esta máquina es ideal para cumplir, de forma eficiente, la meta que te propongas. Eficiencia y calidad Imprimí fácilmente todo lo que quieras con esta impresora HP, ya sean pocas páginas o grandes proyectos. Perfecta para tu hogar o la oficina Si buscás realizar grandes tiradas en pocos minutos, su tecnología láser es ideal para vos. Es simple y fácil de usar y tiene un costo de mantenimiento significativamente menor que las que funcionan a tinta. Conectividad móvil Ahora podés imprimir fácilmente desde tu celular o tablet sin importar en donde te encuentres y sin la asistencia de una computadora. Disfrutá de sus soluciones de impresión móvil, utilizá la que más te guste y tené tus documentos en solo segundos.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1443570224",
    title: "Hp 15.6 Touch-screen I3 8gb 256gb Ssd",
    image: "http://http2.mlstatic.com/D_981994-MLU69221213859_052023-O.jpg",
    price: 300000,
    category: "MLA1652",
    stock: 1,
    sold: 0,
    description:
      "La Notebook HP Laptop 15-dy2702dx en color plateado es la compañera perfecta para tus tareas diarias y entretenimiento. Con su pantalla táctil de 15.6 pulgadas, disfrutarás de una experiencia visual nítida y cómoda al navegar, trabajar o ver tus series favoritas. Gracias a sus 8 GB de memoria RAM DDR4, podrás realizar múltiples tareas de manera eficiente y sin interrupciones. Además, su capacidad de almacenamiento SSD de 256 GB te permitirá guardar todos tus archivos y documentos importantes con rapidez y seguridad. Equipada con un procesador Intel de alto rendimiento, esta notebook te brindará la potencia necesaria para enfrentar cualquier desafío. El sistema operativo Windows te garantiza una experiencia de usuario amigable y versátil. Por último, su batería de ion de litio te proporcionará horas de autonomía para que puedas trabajar o disfrutar de tus contenidos favoritos sin preocuparte por recargarla constantemente. No esperes más y lleva tu productividad al siguiente nivel con la Notebook HP Laptop 15-dy2702dx.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1451214188",
    title:
      "Notebook Hp 15-ef2529la Plata Natural 15.6  Amd Ryzen 5 5500u  8gb De Ram 512gb Ssd Amd Radeon Rx Vega 7 1920x1080px Windows 11 Home",
    image: "http://http2.mlstatic.com/D_877931-MLA69378170816_052023-O.jpg",
    price: 346999,
    category: "MLA1652",
    stock: 100,
    sold: 50,
    description:
      "La notebook HP 15-ef2529la es una solución tanto para trabajar y estudiar como para entretenerte. Al ser portátil, el escritorio dejará de ser tu único espacio de uso para abrirte las puertas a otros ambientes ya sea en tu casa o en la oficina. Pantalla con gran impacto visual Su pantalla de 15.6 y 1920x1080px de resolución te brindará colores más vivos y definidos. Tus películas y series preferidas cobrarán vida, ya que ganarán calidad y definición en cada detalle. Eficiencia a tu alcance Su procesador AMD Ryzen 5 de 6 núcleos, te permitirá ejecutar programas variados y procesos indispensables para desenvolverte en el día a día, ya sea en tu trabajo o en los momentos de ocio en tu hogar. Potente disco sólido El disco sólido de 512 GB hace que el equipo funcione a gran velocidad y por lo tanto te brinda mayor agilidad para operar con diversos programas. Un procesador exclusivo para los gráficos Su placa de video AMD Radeon RX Vega 7 convierte a este dispositivo en una gran herramienta de trabajo para cualquier profesional del diseño. Te permitirá lograr una gran performance en todos tus juegos y en otras tareas cotidianas que impliquen procesamiento gráfico. Una batería que acompaña tu jornada La batería de este equipo tiene una autonomía de alrededor de 9 horas. La duración varía según el uso, la configuración y otros factores, pero vas a poder usarla durante varias horas sin depender de los enchufes.",
    AdminUser: "NULL",
  },
  {
    id: "MLA1452741120",
    title:
      "Notebook Hp 240 G7 Plateado Ceniza Oscuro 14  Intel Core I3 1005g1  8gb De Ram 1tb Hdd Intel ",
    image: "http://http2.mlstatic.com/D_694019-MLA46479872032_062021-O.jpg",
    price: 349999,
    category: "MLA1652",
    stock: 1,
    sold: 2,
    description:
      "La notebook HP 240 G7 es una solución tanto para trabajar y estudiar como para entretenerte. Al ser portátil, el escritorio dejará de ser tu único espacio de uso para abrirte las puertas a otros ambientes ya sea en tu casa o en la oficina. Pantalla con gran impacto visual Su pantalla LED de 14 y 1366x768px de resolución te brindará colores más vivos y definidos. Tus películas y series preferidas cobrarán vida, ya que ganarán calidad y definición en cada detalle. Eficiencia a tu alcance Su procesador Intel Core i3 de 2 núcleos, está pensado para aquellas personas generadoras y consumidoras de contenidos. En base a esto, permite el desempeño necesario para la edición de fotografías o videos en programas básicos. Un procesador exclusivo para los gráficos Su placa de video Intel UHD Graphics G1 (Ice Lake 32 EU) convierte a este dispositivo en una gran herramienta de trabajo para cualquier profesional del diseño. Te permitirá lograr una gran performance en todos tus juegos y en otras tareas cotidianas que impliquen procesamiento gráfico. Una batería de larga duración La batería de este equipo tiene una autonomía de alrededor de 12.3 horas. La duración varía según el uso, la configuración y otros factores, pero es ideal para quienes necesitan extender su jornada y seguir trabajando o estudiando con comodidad y sin cables.",
    AdminUser: "NULL",
  },
  {
    id: "MLA700586854",
    title:
      "Cartucho Hp 664 Original Tricolor Hp 3775 3785 4535 4675 Tienda Oficial Hp",
    image: "http://http2.mlstatic.com/D_683972-MLA69958170840_062023-O.jpg",
    price: 12999,
    category: "MLA7415",
    stock: 1,
    sold: 500,
    description:
      "Cartucho de Tinta HP 664 F6V28AL TRICOLOR original 3775 3785 - F6V28AL  Descripción general Imprima fotografías color con calidad de laboratorio y documentos de todos los días con los económicos cartuchos de tinta original HP de bajo costo, diseñados con protección contra fraudes y alertas inteligentes de poca tinta, para ofrecer un rendimiento libre de preocupaciones y resultados uniformes en los que puede contar. - Color(es) de consumibles de impresión: De tres colores - Gota de tinta: 3,25 pl, 6,8 pl - Tipos de tinta: Basada en colorantes - Rendimiento de la página (color): 100 páginas - Margen de temperaturas operativas: 15 a 32°C - Temperatura de almacenamiento: límites -40 a 60°C - Humedad durante almacenamiento De 20 a 80% HR - Impresoras compatibles: HP DeskJet 1110, HP DeskJet 1115, HP DeskJet 2130, HP DeskJet 2135, HP DeskJet 3630, HP ENVY 4520, HP OfficeJet 3830",
    AdminUser: "NULL",
  },
  {
    id: "MLA881181842",
    title: "Hp Smart Tank 515 - Negro - 200v - 240v",
    image: "http://http2.mlstatic.com/D_962058-MLA41235635226_032020-O.jpg",
    price: 174417,
    category: "MLA1676",
    stock: 1,
    sold: 100,
    description:
      "HP está orgulloso de proveer las impresoras más seguras del mundo. Con ellas conseguirás proteger tu información, obtener lo máximo en tecnología y un rendimiento impresionante que con seguridad se adaptará a cualquier reto que tengas. Siempre están listas para ayudar a cumplir cualquier meta y nunca quedarse atrás en momentos inoportunos. Perfecta para tu hogar o la oficina Al ser a tinta te permitirá lograr impresiones de gran calidad con colores vivos y degradados suaves. Ocupa poco espacio y es fácil de manejar lo que la convierte en la opción ideal para cuestiones laborales, tareas escolares y requerimientos de la vida diaria.",
    AdminUser: "NULL",
  },
  {
    id: "MLA884968586",
    title: "Cabezal Hp Tricolor 5820/5810 Tank 115/315/410/415/515/615",
    image: "http://http2.mlstatic.com/D_897755-MLA46076770922_052021-O.jpg",
    price: 27999.2,
    category: "MLA7415",
    stock: 5000,
    sold: 500,
    description:
      "NUESTROS CABEZALES TIENEN FECHA DE VENCIMIENTOS FINALES DEL AÑO 2024 Y GARANTÍA REAL.!!! LOS CARTUCHOS DE TINTA TIENEN UNA FECHA DE VENCIMIENTO CON EL FIN DE PROTEGER EL SISTEMA DE IMPRESIÓN Y GARANTIZAR LA CALIDAD DE LA MISMA. NUESTROS CABEZALES TIENEN FECHA DE VENCIMIENTO FINALES DEL AÑO 2024, CON GARANTÍA OFICIAL HP DE 3 MESES, NO SE DEJE ENGAÑAR CON CABEZALES VENCIDOS Y GARANTÍA FALSA, EVÍTESE PROBLEMAS. SELECCIONE EL MODELO DE CABEZAL PARA SU IMPRESORA Y ASI EVITAR ERRORES. DESPUES DE LA COMPRA ACLARAR NUEVAMENTE POR LOS CANALES DE COMUNICACION PARA QUE MODELO DE IMPRESORA CORRESPONDE SU COMPRA, HASTA QUE NO RECIBAMOS SU AVISO, NO ENVIAREMOS EL PEDIDO. ATENCION----ATENCION----ATENCION ESTA PABLICACION SI ES COMBATIBLE CON HP SMART TANK 515 / HP SMART TANK 530 / HP SMART TANK 533 / HP INK TANK 615/ HP INK TANK 630.",
    AdminUser: "NULL",
  },
  {
    id: "MLA902037857",
    title: "Cargador Hp Original Pavilion Sleekbook 14-b0 15-b000 +cable",
    image: "http://http2.mlstatic.com/D_955891-MLA44398156757_122020-O.jpg",
    price: 11110,
    category: "MLA3577",
    stock: 1,
    sold: 5,
    description:
      "Cargador HP Envy, Ppp009d 693715-001. POWER CORD 220V INCLUIDO. AC Input: 100V ~ 240V, 50~ 60Hz DC Output: 19.5V - 3.33A , 65 Watt Conector: 4.8mm*1.7mm Cord Cable: CABLE A LA PARED INCLUIDO. Compatibles para los modelos: HP Pavilion Sleekbook 14-b000 15-b000 Series: HP Pavilion Sleekbook 14-b000ed 14-b000ee 14-b000ei 14-b000eo 14-b000et  14-b001ea 14-b001eia 14-b001tx 14-b002tx 14-b004tu 14-b005au 14-b006au  14-b007au 14-b008au 14-b009au 14-b009tu 14-b010au 14-b010us 14-b012au  14-b013au 14-b014au 14-b014tu 14-b015au 14-b015dx 14-b022au 14-b023tx  14-b024tu 14-b025tu 14-b028au 14-b028tu 14-b030tu 14-b031tu 14-b034tu  14-b035tu 14-b038tu 14-b043tu 14-b062la CTO 14z-b000 14-b109wm HP Pavilion Sleekbook 15-b119sl 15-b119ss 15-b120sw 15-b120us 15-b123es  15-b123nr 15-b123ss 15-b124sl 15-b125sb 15-b125sl 15-b128el 15-b128es 15-b129el  15-b129es 15-b130eb 15-b130sc 15-b130sw 15-b131el 15-b135ea 15-b140el  HP ENVY Pro Ultrabook 4 HP ENVPR4 i5-3317U HP SpectreXT Pro i5-3317U HP SpectreXT Pro i5-3337U HP SpectreXT Pro i5-3567U HP SpectreXT Pro i7-3537U HP ENVY 4 Series HP ENVY 6 Series.",
    AdminUser: "NULL",
  },
  {
    id: "MLA903380389",
    title: "Hp Deskjet Ink Advantage 2775 - Blanco - 200v - 240v",
    image: "http://http2.mlstatic.com/D_604241-MLA44220449156_122020-O.jpg",
    price: 56795.16,
    category: "MLA1676",
    stock: 50,
    sold: 500,
    description:
      "HP está orgulloso de proveer las impresoras más seguras del mundo. Con ellas conseguirás proteger tu información, obtener lo máximo en tecnología y un rendimiento impresionante que con seguridad se adaptará a cualquier reto que tengas. Siempre están listas para ayudar a cumplir cualquier meta y nunca quedarse atrás en momentos inoportunos. Perfecta para tu hogar o la oficina Al ser a tinta te permitirá lograr impresiones de gran calidad con colores vivos y degradados suaves. Ocupa poco espacio y es fácil de manejar lo que la convierte en la opción ideal para cuestiones laborales, tareas escolares y requerimientos de la vida diaria. Conectividad móvil Ahora podés imprimir fácilmente desde tu celular o tablet sin importar en donde te encuentres y sin la asistencia de una computadora. Disfrutá de sus soluciones de impresión móvil, utilizá la que más te guste y tené tus documentos en la mano en solo segundos.",
    AdminUser: "NULL",
  },
  {
    id: "MLA903408738",
    title: "Cargador Hp Elitebook 725 745 840 850 G3 Original 45w-65w",
    image: "http://http2.mlstatic.com/D_664410-MLA44532463816_012021-O.jpg",
    price: 7067.07,
    category: "MLA3577",
    stock: 100,
    sold: 500,
    description:
      "CARGADOR ORIGINAL HP Elitebook 725 745 840 850 G3 ENVY 4 6 PAVILLON TOUCHSMART 14 15 19.5V- 3.33A NO INCLUYE CABLE POWER! Características: Entrada: 100-240v, 50-60 hz Salida: 19.5v 3.33a Potencia: 65W Ficha: 4.5 x 3.0 mm. Tipo: Original Modelos compatibles: HP Pavilion Sleekbook 14-B, 14Z-B, 15-B, 15T-B Series HP Pavilion Chromebook 14-C Series HP ENVY Spectre XT Pro Ultrabook 13, 14, NV13, NV14 Series HP Spare 677770-003, 677770-001,677770- 002, 613149-003, 693715-001 Laptops HP Pavilion Sleekbook Series Ultraportable. HP ENVY Sleekbook 6-1000 Series- HP ENVY Sleekbook series. HP ENVY 4/6 Series Ultraportable Laptop Somos Distribuidores Oficiales de todas las Marcas. que Trabajamos, Garantías Oficiales en Argentina. HACEMOS FACTURA B UNICAMENTE!!! Estamos a pocas cuadras de la facultad de ciencias sociales del barrio Monserrat y de la estación de subte linea E. Atendemos de Lunes a Viernes de corrido de 11 a 18 hs, sábados de 11hs a 14hs. Domingos y feriados, cerrado. Sábados, Domingos y feriados, cerrado.",
    AdminUser: "NULL",
  },
  {
    id: "MLA913334049",
    title:
      "Impresora A Color MultifunciÃ³n Hp Smart Tank 530 Con Wifi Negra 100v/240v",
    image: "http://http2.mlstatic.com/D_717117-MLA45074626662_032021-O.jpg",
    price: 189106,
    category: "MLA1676",
    stock: 1,
    sold: 150,
    description:
      "HP está orgulloso de proveer las impresoras más seguras del mundo. Con ellas conseguirás proteger tu información, obtener lo máximo en tecnología y un rendimiento impresionante que con seguridad se adaptará a cualquier reto que tengas. Siempre están listas para ayudar a cumplir cualquier meta y nunca quedarse atrás en momentos inoportunos. Perfecta para tu hogar o la oficina Al ser a tinta te permitirá lograr impresiones de gran calidad con colores vivos y degradados suaves. Ocupa poco espacio y es fácil de manejar lo que la convierte en la opción ideal para cuestiones laborales, tareas escolares y requerimientos de la vida diaria. Conectividad móvil Ahora podés imprimir fácilmente desde tu celular o tablet sin importar en donde te encuentres y sin la asistencia de una computadora. Disfrutá de sus soluciones de impresión móvil, utilizá la que más te guste y tené tus documentos en la mano en solo segundos.",
    AdminUser: "NULL",
  },
  {
    id: "MLA926944120",
    title: "Mini Hp Pc 260 G4 Celeron 5205u 8gb 240gb Ssd Windows 10  ",
    image: "http://http2.mlstatic.com/D_644326-MLA46506816458_062021-O.jpg",
    price: 251571.17,
    category: "MLA1649",
    stock: 1,
    sold: 5,
    description:
      "El equipo de escritorio HP Pro Mini 260 proporciona a los usuarios rendimiento y funciones de nivel empresarial en un chasis compacto. Este equipo viene con el último procesador Intel®[2] y ofrece diversas funciones para satisfacer los requisitos diarios de su empresa a un precio asequible.",
    AdminUser: "NULL",
  },
];

module.exports = productos;
